development:
  :address: smtpout.secureserver.net
  :port: 80
  :Domain: mail.google.com
  :authentication: plain
  :user_name: info@codestains.com
  :password: code@12345
  :enable_starttls_auto: true       

production:
  :address: smtpout.secureserver.net
  :port: 80
  :Domain: mail.google.com
  :authentication: plain
  :user_name: info@codestains.com
  :password: code@12345
  :enable_starttls_auto: true
